### Get all Invoices
GET /api/v1/invoices HTTP/1.1
Host: localhost:3000

### Create new Invoice
POST /api/v1/invoices HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "item": "Contract Project Budget",
  "quantity": 2,
  "amount": 200.00,
  "tax": 2.00,
  "date": "2020-01-01",
  "dueDate": "2020-03-01"
}