### Get all Invoices
GET /api/v1/invoices HTTP/1.1
Host: localhost:3001
Authorization: Bearer {{auth_token}}

### Create new Invoice
POST /api/v1/invoices HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
  "item": "Azure & AWS Cloud Infrastructure Budget",
  "quantity": 2,
  "amount": 2200.00,
  "tax": 29.52,
  "date": "2020-01-01",
  "dueDate": "2022-03-01",
   "client": "62019a32783124a71a036a1f"
}

### Get Invoice by ID
GET /api/v1/invoices/61fc79b686c2a60e1b0f8ca3 HTTP/1.1
Host: localhost:3001
Authorization: Bearer {{auth_token}}


### Update Invoice by ID
PUT /api/v1/invoices/61fc79b686c2a60e1b0f8ca3 HTTP/1.1
Host: localhost:3001
Content-Type: application/json

{
  "item": "Microsoft Project Budget",
  "quantity": 2,
  "amount": 300.00,
  "tax": 2.00,
  "date": "2020-01-01",
  "dueDate": "2020-03-02"
}

### Delete Invoice by ID
DELETE /api/v1/invoices/61fc79b686c2a60e1b0f8ca3 HTTP/1.1
Host: localhost:3001

### Query Invoices by Page & Limit
GET /api/v1/invoices?page=1&perPage=5 HTTP/1.1
Host: localhost:3001

### Filter Invoices by item name
GET /api/v1/invoices?filter=Angular HTTP/1.1
Host: localhost:3001


### Filter Invoices by sortField & sortDir
GET /api/v1/invoices?sortField=item&sortDir=asc HTTP/1.1
Host: localhost:3001